### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by webparadoxer** [uPagge/gitlab-notification#19]
Положите плиз в репу пример docker-compose с pg внутри

**Comment by reysonk** [comment]
Мой пример рабочего конфига
```
version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "gitlab_bot"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "!XxXxXxX!"
      PGDATA: "/data/postgres"
    volumes:
       - /var/dockervol/gitlab-bot/data/postgres:/data/postgres
       - /var/dockervol/gitlab-bot/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
########################
#можно убрать если не хочется посмотреть что там внутри БД
########################
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 4580:8080
########################
  glbot:
    image: upagge/gitlab-telegram-notify
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "xxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      TELEGRAM_BOT_USERNAME: "@xxxxxxx_gitlab_bot"
      GITLAB_PERSONAL_TOKEN: "xxxxxxxxxxxxxxxxxxxxx"
      TELEGRAM_PERSON_ID: "xxxxxxx"
      GITLAB_URL: "https://git.xxxxxx.ru"
      DATASOURCE_URL: "jdbc:postgresql://db:5432/gitlab_bot"
      DATASOURCE_USERNAME: "postgres"
      DATASOURCE_PASSWORD: "!XxXxXxX!"
```
